import { TestSuite } from './models';
import { generateBasePage, generatePageObject } from './pomGenerator';
import { generateSpecFile } from './specGenerator';
import { STATE_STORE_TEMPLATE, API_MANAGER_TEMPLATE, CORE_INDEX_TEMPLATE } from './coreFramework';

export * from './models';

export interface GeneratedFile {
  filename: string;
  content: string;
}

/**
 * Main entry point for the UPAF Code Generator.
 * Takes a JSON TestSuite and generates a complete Playwright repository structure.
 */
const AUTO_GENERATED_HEADER = `/**
 * ⚠️ WARNING: THIS FILE IS AUTO-GENERATED BY UPAF. 
 * DO NOT EDIT THIS FILE MANUALLY. 
 * ANY CHANGES WILL BE OVERWRITTEN ON NEXT EXPORT.
 */\n\n`;

export function generatePlaywrightProject(suite: TestSuite): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. Generate Core Framework files for API Testing
  files.push({
    filename: 'tests/upaf-generated/core/StateStore.ts',
    content: AUTO_GENERATED_HEADER + STATE_STORE_TEMPLATE,
  });

  files.push({
    filename: 'tests/upaf-generated/core/ApiManager.ts',
    content: AUTO_GENERATED_HEADER + API_MANAGER_TEMPLATE,
  });

  files.push({
    filename: 'tests/upaf-generated/core/index.ts',
    content: AUTO_GENERATED_HEADER + CORE_INDEX_TEMPLATE,
  });

  // 2. Generate BasePage
  files.push({
    filename: 'tests/upaf-generated/pages/BasePage.ts',
    content: AUTO_GENERATED_HEADER + generateBasePage(),
  });

  // 3. Generate Page Object for the Suite
  // For simplicity, we use the Suite title to name the POM, removing spaces.
  const pomClassName = suite.title.replace(/[^a-zA-Z0-9]/g, '') + 'Page';
  files.push({
    filename: `tests/upaf-generated/pages/${pomClassName}.ts`,
    content: AUTO_GENERATED_HEADER + generatePageObject(pomClassName, suite),
  });

  // 4. Generate Spec File
  const specFileName = suite.title.replace(/[^a-zA-Z0-9-]/g, '_').toLowerCase() + '.spec.ts';
  files.push({
    filename: `tests/upaf-generated/${specFileName}`,
    content: AUTO_GENERATED_HEADER + generateSpecFile(suite, pomClassName),
  });

  // 5. Generate playwright.config.ts
  files.push({
    filename: 'playwright.config.ts',
    content: `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests', // Runs both custom and upaf-generated tests
  fullyParallel: true,
  reporter: 'html',
  use: {
    baseURL: '${suite.baseUrl}',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`
  });

  return files;
}
